import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "../components/common/Navigation";
import { Toaster } from "@/components/ui/toaster";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "PoC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-auto`}
      >
        <div className="container mx-auto">
          <Navigation />
        </div>
        <div className="bg-blue-50 min-h-screen">
          <main className="container flex flex-col gap-4 row-start-2 items-center sm:items-start mx-auto pt-3">
            <ReactQueryProvider>
            {children}
            </ReactQueryProvider>
            <Toaster />
          </main>
        </div>

      </body>
    </html>
  );
}
