/* tslint:disable */
/* eslint-disable */
/**
 * Get users endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  User,
} from '../models/index';
import {
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface 1494a6ac280430b7c87ec3bdc6c4bff2Request {
    uuid: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get one user by it\'s UUID
     */
    async _1494a6ac280430b7c87ec3bdc6c4bff2Raw(requestParameters: 1494a6ac280430b7c87ec3bdc6c4bff2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling _1494a6ac280430b7c87ec3bdc6c4bff2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/users/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Get one user by it\'s UUID
     */
    async _1494a6ac280430b7c87ec3bdc6c4bff2(requestParameters: 1494a6ac280430b7c87ec3bdc6c4bff2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this._1494a6ac280430b7c87ec3bdc6c4bff2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all users
     */
    async _566aed8efb436ca506e0ef51a032ecd9Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Get all users
     */
    async _566aed8efb436ca506e0ef51a032ecd9(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this._566aed8efb436ca506e0ef51a032ecd9Raw(initOverrides);
        return await response.value();
    }

}
